import "@/styles/globals.css";
import type { ReactNode } from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";

type RootLayoutProps = Readonly<{ children: ReactNode }>;

const geistSans = localFont({ src: "../fonts/GeistVF.woff", variable: "--font-geist-sans", weight: "100 900" });
const geistMono = localFont({ src: "../fonts/GeistMonoVF.woff", variable: "--font-geist-mono", weight: "100 900" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  generator: `Next.js ${process.env.NEXT_VERSION}`.trim(),
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="ko">
      <body id="__next" className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
