import "@/styles/globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { QueryStreamingProvider } from "@/components/provider/QueryProvider";
import StoreProvider from "@/components/provider/StoreProvider";

type RootLayoutProps = Readonly<{ children: React.ReactNode }>;

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  generator: `Next.js ${process.env.PACKAGE_NEXT_VERSION ?? ""}`.trim(),
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <StoreProvider>
      <html lang="ko-KR" suppressHydrationWarning>
        <body id="__next" className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning>
          <QueryStreamingProvider>
            {children}
            <div id="root_modal" />
          </QueryStreamingProvider>
        </body>
      </html>
    </StoreProvider>
  );
}
