const NODE_ENV = process.env;

export const ENV_BUILD_AT = NODE_ENV.BUILD_AT;
export const ENV_BUILD_TS = NODE_ENV.BUILD_TS;
export const ENV_BUILD_HASH = NODE_ENV.BUILD_HASH;

export const ENV_NEXT_VERSION = NODE_ENV.NEXT_VERSION;
export const ENV_PACKAGE_NAME = NODE_ENV.NEXT_PUBLIC_PACKAGE_NAME;
export const ENV_PACKAGE_VERSION = NODE_ENV.NEXT_PUBLIC_PACKAGE_VERSION;

export const ENV_IS_MAINTENANCE = NODE_ENV.NEXT_PUBLIC_IS_MAINTENANCE;

export const ALL_ENV = {
  BUILD_AT: ENV_BUILD_AT,
  BUILD_TS: ENV_BUILD_TS,
  BUILD_HASH: ENV_BUILD_HASH,
  NEXT_VERSION: ENV_NEXT_VERSION,
  PACKAGE_NAME: ENV_PACKAGE_NAME,
  PACKAGE_VERSION: ENV_PACKAGE_VERSION,
  IS_MAINTENANCE: ENV_IS_MAINTENANCE,
};
